version: '2'
services:
  web:
    build: .
    environment:
     - APP_API_GATEWAY=http://backend:8080
     - APP_API_PLACEHOLDER=/api
    ports:
     - "8081:80"
  backend:
    build: backend/
    ports:
      - "8080:8080"