version: '2'
services:
  web:
    image: swingevents_web
    environment:
     - APP_API_GATEWAY=http://backend:8080
     - APP_API_PLACEHOLDER=/api
    ports:
     - "80:80"
     - "443:443"
  backend:
    image: swingevents_backend